import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  download
} from "../assets/images/index";


export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];

export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Earrings",
    price: "35000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: "2011",
    img: download,
    productName: "ring",
    price: "35000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Earring",
    price: "18000.00",
    color: "Gray",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Mangalsutra",
    price: "25000.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "MangalSutra",
    price: "22000.00",
    color: "Black",
    badge: true,
    des: "prajwalsoni",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Jewellery1",
    price: "35000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Jewellery2",
    price: "180000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Jewellery",
    price: "25000.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Jewellery21",
    price: "22000.00",
    color: "Black",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Jewellery21",
    price: "35000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Jewellery32",
    price: "180000.00",
    color: "Gray",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Jewellery222",
    price: "25000.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Jewellery212",
    price: "22000.00",
    color: "Golden",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Jewellery121",
    price: "44000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Jewellery42",
    price: "250.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Jewellery41",
    price: "80.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Ring",
    price: "60000.00",
    color: "Golden",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Pendant",
    price: "60000.00",
    color: "Mixed",
    badge: false,
    des: "prajwalsoni",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Pendant",
    price: "25000.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Jewellery201",
    price: "60.00",
    color: "Golden",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Jewellery202",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Jewellery203",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Jewellery204",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Jewellery205",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "Jewellery206",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Jewellery207",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Jewellery208",
    price: "220.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Jewellery209",
    price: "35.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Jewellery232",
    price: "35.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Jewellery210",
    price: "180.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Jewellery21",
    price: "25.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Jewellery401",
    price: "220.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Jewellery201",
    price: "35.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "Jewellery400",
    price: "180.00",
    color: "Golden",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Jewellery227",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Jewellery226",
    price: "220.00",
    color: "Golden",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Jewellery225",
    price: "44.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Jewellery224",
    price: "250.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "Jewellery223",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Jewellery222",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Jewellery221",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Jewellery220",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Jewellery219",
    price: "250.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Jewellery218",
    price: "220.00",
    color: "Golden",
    badge: false,
    des: "prajwalsoni",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Jewellery217",
    price: "44.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Jewellery216",
    price: "250.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Jewellery215",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Jewellery214",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Jewellery213",
    price: "220.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Jewellery212",
    price: "35.00",
    color: "Golden",
    badge: true,
    des: "prajwalsoni",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Jewellery211",
    price: "35.00",
    color: "Golden",
    badge: true,
   
  },
];

